name: 'C++ CI'

on:
  push:
    branches:
      - master
      - hw1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - run: sudo apt-get update && sudo apt-get install libboost-test-dev ninja-build -y
      - run: cmake . -DPATCH_VERSION=${{ github.run_number }} -DWITH_BOOST_TEST=ON -G Ninja
      - run: cmake --build .
      - run: cmake --build . --target test
      - run: cmake --build . --target package
      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.run_number }}
          name: Release ${{ github.run_number }}
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: "*.tar.gz,*.deb"
      # - name: Upload Release Asset
      #   id: upload-release-asset
      #   uses: actions/upload-release-asset@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     upload_url: ${{ steps.create_release.outputs.upload_url }}
      #     asset_path: ./helloworld-0.0.${{ github.run_number }}-Linux.deb
      #     asset_name: helloworld-0.0.${{ github.run_number }}-Linux.deb
      #     asset_content_type: application/vnd.debian.binary-package